---
name: Build

on:
  push:
    branches: ['develop', 'release/**', 'master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GHA
        uses: benc-uk/workflow-dispatch@v1
        with:
          inputs: '{ "BRANCH": "${{ github.ref }}" }'
          ref: 'develop',
          repo: netdata/cloud-sso
          token: ${{ secrets.NETDATABOT_TOKEN }}
          workflow: main
